### ISSUE TITLE
[feature request] prepend shorthand integer to available packages to avoid typing long package names

### ISSUE THREAD

**Issue by marco-piccolino** [Cutehacks/qpm#12]
as above

**Comment by jrbarron** [comment]
@marco-piccolino Interesting suggestion. Another suggestion though was to support only the final part of the package name (see #6). So if you typed `qpm install quickflux` it would do the right thing if the package name was unique or would warn you if there were multiple packages with that name. Would implementing that solve this or do you still think that an integer is needed?

**Comment by marco-piccolino** [comment]
@jrbarron that'd do as well, and it makes it independent from the output of qpm list.
Ben's suggestion was a bit buried in that post.
