### ISSUE TITLE
How to register third party repository as a qpm package?

### ISSUE THREAD

**Issue by molchanoviv** [Cutehacks/qpm#20]
Does qpm support fetching libraries from repositories which does not registered as a package? I think this feature will make qpm useful at the first stages until all the libraries are registered.

**Comment by benlau** [comment]
I don't think it is supported. But I vote for this feature too.

There are several more use cases
1. May fetch from private repo
2. Development version testing

For example, developer may fix a bug in git repo and let reporter to test it before publish.

https://github.com/benlau/quickandroid/issues/16

**Comment by jrbarron** [comment]
I have discussed this a bit with @mariusbu and I think the best way to support this would be through Git submodules. Let's take a concrete example. If you wanted to provide a Qt/QML wrapper around Box2d, you could add this dependency as a git submodule in your project's repository. All the information describing the package would live in your repository and not in the Box2D repository. When qpm installs your wrapper package (which is published to qpm.io) then it will also recursively checkout any submodules (perhaps up to a specified depth).

Currently qpm is using the Github tarball API, but there are several problems with this approach so we are transitioning to using `git clone` for downloading packages. Once this transition is done, we can start making better use of Git's features such as submodules.

The issue that pops up here though is what if two packages both have different versions of the same submodule. That could lead to compile issues. Not really sure how to solve that one..

**Comment by mariusbu** [comment]
Just FYI, I've pushed a change so we now do 'git clone --recursive'. There is no mechanism for handling clashing submodules in different packages, but I'm not sure if that is a problem we should try to handle at all (packages can have clashing symbols in other ways too).

**Comment by mariusbu** [comment]
The official v0.11.0 release now supports GIT as a repository type and will use `git clone --recursive` to clone repo + submodules.
