### ISSUE TITLE
Wrong path of qpm.json

### ISSUE THREAD

**Issue by kafeg** [Cutehacks/qpm#24]
Hi.

I will try to install my library after publishing. Result:

```
d:\example>qpm install com.github.qtrest
INFO: Package com.github.qtrest has a different license (MIT) than it's dependant (NONE).
Installing com.github.qtrest@0.1.0
QPM: 2016/03/10 21:14:53 ERROR: GetFileAttributesEx 
d:\example\vendor\kafeg-qtrest-d9cb6cf\src\models\qpm.json: 
The system cannot find the file specified.
```

What does it mean? My qpm.json available in d:\example\vendor\kafeg-qtrest-d9cb6cf\qpm.json. Why qpm try to find it in subdirectory `\src\models`?

**Comment by jrbarron** [comment]
@kafeg Strange, I just tried on Mac OS and it worked fine for me. Perhaps it is something Windows specific. I will take a look tomorrow since I don't have access to a Windows machine right now. In the meantime, thanks for contributing!

**Comment by bgr** [comment]
I am having the same problem, and also another similar one that seems related:

```
INFO: Package com.github.benlau.quickflux has a different license (APACHE_2_0) than it's dependant (NONE).
Installing com.github.benlau.quickflux@1.0.4
QPM: 2016/03/15 21:54:15 ERROR: GetFileAttributesEx D:\dev\meh\vendor\benlau-quickflux-e81d71d\tests\qmlunittests\qpm.json: The system cannot find the file specified.
```

```
INFO: Package com.github.benlau.qsyncable has a different license (APACHE_2_0) than it's dependant (NONE).
Installing com.github.benlau.qsyncable@1.0.0
QPM: 2016/03/15 21:54:07 ERROR: rename D:\dev\meh\vendor\benlau-qsyncable-ce649d0\tests\qsyncableunittests D:\dev\meh\vendor: The system cannot find the path specified.
```

**Comment by jrbarron** [comment]
I can reproduce this on Windows. I'm not sure what causes it yet, but will do some debugging and post an update. It seems to only affect certain repositories which is also strange.

**Comment by kafeg** [comment]
Hi. If it's important, on my system Win 8.1 installed Unxutils. I think it is not the cause, but you never know what =)

**Comment by jrbarron** [comment]
@kafeg @bgr This fix is working it's way through the CI system now, when it goes green, the fix should be available here:

https://storage.googleapis.com/www.qpm.io/download/latest/windows_amd64/qpm.exe
https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm.exe

**Comment by kafeg** [comment]
Hi! Thanks for fix! I will check it today.

**Comment by kafeg** [comment]
Hi.

Last build did not fix issue.

qpm@0.10.0 from your url:

C:\dev\qtrest-example>qpm_last.exe install com.github.kafeg.qtrest
INFO: Package com.github.kafeg.qtrest has a different license (MIT) than it's dependant (NONE).
Installing com.github.kafeg.qtrest@0.1.0
QPM: 2016/04/03 14:36:03 ERROR: GetFileAttributesEx C:\dev\qtrest-example\vendor\kafeg-qtrest-2dddaa5\src\models\qpm.json: The system cannot find the file specified.

**Comment by yuriio147** [comment]
Hi, Im also able to reproduce this issue. qpm@0.10.0 . Win7 x64
D:\Qt>qpm install com.github.benlau.quickflux
INFO: Package com.github.benlau.quickflux has a different license (APACHE_2_0) than it's dependant (NONE).
Installing com.github.benlau.quickflux@1.0.5.4
QPM: 2016/06/25 20:59:57 ERROR: GetFileAttributesEx D:\Qt\vendor\benlau-quickflux-38e3bda\tests\quic
kfluxunittests\qmltests\qpm.json: The system cannot find the file specified.

**Comment by mariusbu** [comment]
Hi, I'm able to reproduce this on my windows machine. It seems that the qpm.json file is located one directory up from where qpm expects to find it. I'm investigating why this is the case and why this seems to work fine on Mac OS.

**Comment by mariusbu** [comment]
After building the latest version of qpm from master I can no longer reproduce this problem, so I think @jrbarron has fixed this issue in the repo. @jrbarron The binary that is available from qpm.io seems to still have this problem, so I think we just need to update that one.

**Comment by 0xlitf** [comment]
I build the qpm by myself, it works.
go get qpm.io/qpm
go build qpm.io/qpm

evn: go 1.8.1 Windows 10
