### ISSUE TITLE
Howto change package name or remove it from registry?

### ISSUE THREAD

**Issue by kafeg** [Cutehacks/qpm#25]
If i won to remove my package after wrong publishing or rename it (e.g. com.github.qtrest to com.github.kafeg.qtrest) how i may to do that?

**Comment by jrbarron** [comment]
@kafeg That feature is sadly not implemented yet, but I can manually remove it from the database if you like?

**Comment by kafeg** [comment]
Yes please remove it. I will republish tomorow with right package name.

**Comment by jrbarron** [comment]
@kafeg Done!

**Comment by kafeg** [comment]
Thanks! =)

**Comment by uralbash** [comment]
@jrbarron Could you remove `ru.uralbash.qmltranslator` too. I republish it with other name.

**Comment by jrbarron** [comment]
@uralbash Done!
