### ISSUE TITLE
The specified key does not exist.

### ISSUE THREAD

**Issue by pamar** [Cutehacks/qpm#26]
There is no key at https://storage.googleapis.com/www.qpm.io/repository.

**Comment by jrbarron** [comment]
Correct, but I don't think this is a problem? That is probably Google's default response if a directory does not support showing it's contents. The Qt maintenance tool expects a file called `Updates.xml` in that directory and that seems to be accessible:

https://storage.googleapis.com/www.qpm.io/repository/Updates.xml

The repository part does not seem to work at the moment though (see bug #16 ), but that does not appear to be related to this bug so I'm going to close this task
