### ISSUE TITLE
Website: Markdown Nested Lists indentation broken

### ISSUE THREAD

**Issue by Skycoder42** [Cutehacks/qpm#37]
It seems that the HTML generated from the markdown README.md fails with lists.

GitHub: https://github.com/Skycoder42/QObjectListModel/blob/master/README.md#features
qpm: https://www.qpm.io/packages/de.skycoder42.qobjectlistmodel/index.html#features

I guess you are using a library for this, so this is probably the wrong place for the issue... Feel free to redirect me.

**Comment by jrbarron** [comment]
@Skycoder42 We are actually using Github's own endpoint for rendering the markdown: https://developer.github.com/v3/repos/contents/#get-the-readme

It looks like that endpoint is properly rendering the nested list so it must be something with our stylesheet that breaks this. I played around with it and it seems we clear the left-padding on the `<ul>` element which makes all list items render to the same offset. I'll try to fix this soon and republish the package docs. Thanks for the report!

**Comment by jrbarron** [comment]
Should be fixed now.
