### ISSUE TITLE
qpm: 'list' command is missing

### ISSUE THREAD

**Issue by ElderOrb** [Cutehacks/qpm#4]
I understand it is a bit early to talk about this (as qpm packets repository is empty), but would be nice to get 'list' command added to the list of supported commands. Without this command it will be pretty hard to locate the proper module (and get an idea about how many QML modules was uploaded to repository)

**Comment by jrbarron** [comment]
@ElderOrb Completely agree! We'll be adding this in the coming days. You can check out our roadmap here:

https://trello.com/b/ofOIyRR0/qpm-roadmap

Feel free to upvote or comment in items you are interested in :)

**Comment by jrbarron** [comment]
Implemented this in 9f92c5c903bb4608c057efe4bb8f2b5124ff4595

**Comment by ElderOrb** [comment]
Cool, that was fast! :)
