### ISSUE TITLE
Support YAML

### ISSUE THREAD

**Issue by MartinDelille** [Cutehacks/qpm#58]
I'm a big fan of [YAML](https://www.yaml.org) and wondered what would it take to support a `qpm.yaml` file?

**Comment by mariusbu** [comment]
Hi, it would be possible to add support for YAML, given that it seems that it is fairly interchangeable with JSON. This is the first request for YAML support we've received, but we'll keep it in mind for future versions. If you feel like sending a PR, we'll certainly consider it! :)
